---
  - name: Remove apache
    apt: name=apache2 state=absent
  - name: Remove index.html
    file:
      path=/var/www/html/index.html
      state=absent
  - name: Remove info.php
    file:
       path=/var/www/html/info.php
       state=absent
